name: Close Stale Pull Requests
on:
  workflow_call:
  schedule:
    - cron: "41 3 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v4
        with:
          days-before-issue-stale: -1
          days-before-issue-close: -1
          stale-pr-message: "This pull request is stale because it has been open for 15 days with no activity. If you'd like to keep it, consider making it a draft."
          close-pr-message: "This pull request was closed because it has been inactive for 7 days since being marked as stale."
          days-before-pr-stale: 15
          days-before-pr-close: 7
          exempt-draft-pr: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
